// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos/internal_edge.proto
// Protobuf C++ Version: 6.30.2

#ifndef protos_2finternal_5fedge_2eproto_2epb_2eh
#define protos_2finternal_5fedge_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/timestamp.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_protos_2finternal_5fedge_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_protos_2finternal_5fedge_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_protos_2finternal_5fedge_2eproto;
}  // extern "C"
namespace internaledge {
enum ProcessingResponse_Status : int;
extern const uint32_t ProcessingResponse_Status_internal_data_[];
class Job;
struct JobDefaultTypeInternal;
extern JobDefaultTypeInternal _Job_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Job_class_data_;
class Location;
struct LocationDefaultTypeInternal;
extern LocationDefaultTypeInternal _Location_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Location_class_data_;
class ProcessingResponse;
struct ProcessingResponseDefaultTypeInternal;
extern ProcessingResponseDefaultTypeInternal _ProcessingResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ProcessingResponse_class_data_;
class Scan;
struct ScanDefaultTypeInternal;
extern ScanDefaultTypeInternal _Scan_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Scan_class_data_;
class ScanRequest;
struct ScanRequestDefaultTypeInternal;
extern ScanRequestDefaultTypeInternal _ScanRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ScanRequest_class_data_;
}  // namespace internaledge
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::internaledge::ProcessingResponse_Status_internal_data_>
    internal::EnumTraitsImpl::value<::internaledge::ProcessingResponse_Status>;
}  // namespace protobuf
}  // namespace google

namespace internaledge {
enum ProcessingResponse_Status : int {
  ProcessingResponse_Status_SUCCESS = 0,
  ProcessingResponse_Status_FAILURE = 1,
  ProcessingResponse_Status_PARTIAL_SUCCESS = 2,
  ProcessingResponse_Status_ProcessingResponse_Status_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  ProcessingResponse_Status_ProcessingResponse_Status_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t ProcessingResponse_Status_internal_data_[];
inline constexpr ProcessingResponse_Status ProcessingResponse_Status_Status_MIN =
    static_cast<ProcessingResponse_Status>(0);
inline constexpr ProcessingResponse_Status ProcessingResponse_Status_Status_MAX =
    static_cast<ProcessingResponse_Status>(2);
inline bool ProcessingResponse_Status_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int ProcessingResponse_Status_Status_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ProcessingResponse_Status_descriptor();
template <typename T>
const std::string& ProcessingResponse_Status_Name(T value) {
  static_assert(std::is_same<T, ProcessingResponse_Status>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to Status_Name().");
  return ProcessingResponse_Status_Name(static_cast<ProcessingResponse_Status>(value));
}
template <>
inline const std::string& ProcessingResponse_Status_Name(ProcessingResponse_Status value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ProcessingResponse_Status_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool ProcessingResponse_Status_Parse(
    absl::string_view name, ProcessingResponse_Status* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<ProcessingResponse_Status>(ProcessingResponse_Status_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class Location final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:internaledge.Location) */ {
 public:
  inline Location() : Location(nullptr) {}
  ~Location() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Location* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Location));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Location(::google::protobuf::internal::ConstantInitialized);

  inline Location(const Location& from) : Location(nullptr, from) {}
  inline Location(Location&& from) noexcept
      : Location(nullptr, std::move(from)) {}
  inline Location& operator=(const Location& from) {
    CopyFrom(from);
    return *this;
  }
  inline Location& operator=(Location&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Location& default_instance() {
    return *reinterpret_cast<const Location*>(
        &_Location_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Location& a, Location& b) { a.Swap(&b); }
  inline void Swap(Location* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Location* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Location* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Location>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Location& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Location& from) { Location::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Location* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "internaledge.Location"; }

 protected:
  explicit Location(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Location(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Location& from);
  Location(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Location&& from) noexcept
      : Location(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLatitudeFieldNumber = 1,
    kLongitudeFieldNumber = 2,
    kAltitudeFieldNumber = 3,
  };
  // double latitude = 1;
  void clear_latitude() ;
  double latitude() const;
  void set_latitude(double value);

  private:
  double _internal_latitude() const;
  void _internal_set_latitude(double value);

  public:
  // double longitude = 2;
  void clear_longitude() ;
  double longitude() const;
  void set_longitude(double value);

  private:
  double _internal_longitude() const;
  void _internal_set_longitude(double value);

  public:
  // optional double altitude = 3;
  bool has_altitude() const;
  void clear_altitude() ;
  double altitude() const;
  void set_altitude(double value);

  private:
  double _internal_altitude() const;
  void _internal_set_altitude(double value);

  public:
  // @@protoc_insertion_point(class_scope:internaledge.Location)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Location& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    double latitude_;
    double longitude_;
    double altitude_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protos_2finternal_5fedge_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Location_class_data_;
// -------------------------------------------------------------------

class Job final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:internaledge.Job) */ {
 public:
  inline Job() : Job(nullptr) {}
  ~Job() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Job* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Job));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Job(::google::protobuf::internal::ConstantInitialized);

  inline Job(const Job& from) : Job(nullptr, from) {}
  inline Job(Job&& from) noexcept
      : Job(nullptr, std::move(from)) {}
  inline Job& operator=(const Job& from) {
    CopyFrom(from);
    return *this;
  }
  inline Job& operator=(Job&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Job& default_instance() {
    return *reinterpret_cast<const Job*>(
        &_Job_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Job& a, Job& b) { a.Swap(&b); }
  inline void Swap(Job* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Job* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Job* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Job>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Job& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Job& from) { Job::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Job* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "internaledge.Job"; }

 protected:
  explicit Job(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Job(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Job& from);
  Job(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Job&& from) noexcept
      : Job(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kJobIdFieldNumber = 1,
  };
  // int64 job_id = 1;
  void clear_job_id() ;
  ::int64_t job_id() const;
  void set_job_id(::int64_t value);

  private:
  ::int64_t _internal_job_id() const;
  void _internal_set_job_id(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:internaledge.Job)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Job& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int64_t job_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protos_2finternal_5fedge_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Job_class_data_;
// -------------------------------------------------------------------

class Scan final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:internaledge.Scan) */ {
 public:
  inline Scan() : Scan(nullptr) {}
  ~Scan() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Scan* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Scan));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Scan(::google::protobuf::internal::ConstantInitialized);

  inline Scan(const Scan& from) : Scan(nullptr, from) {}
  inline Scan(Scan&& from) noexcept
      : Scan(nullptr, std::move(from)) {}
  inline Scan& operator=(const Scan& from) {
    CopyFrom(from);
    return *this;
  }
  inline Scan& operator=(Scan&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Scan& default_instance() {
    return *reinterpret_cast<const Scan*>(
        &_Scan_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Scan& a, Scan& b) { a.Swap(&b); }
  inline void Swap(Scan* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Scan* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Scan* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Scan>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Scan& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Scan& from) { Scan::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Scan* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "internaledge.Scan"; }

 protected:
  explicit Scan(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Scan(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Scan& from);
  Scan(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Scan&& from) noexcept
      : Scan(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEventIdFieldNumber = 2,
    kSourceFieldNumber = 4,
    kJobFieldNumber = 1,
    kTimestampFieldNumber = 3,
    kLocationFieldNumber = 5,
  };
  // string event_id = 2;
  void clear_event_id() ;
  const std::string& event_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_event_id(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_event_id();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_event_id();
  void set_allocated_event_id(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_event_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_event_id(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_event_id();

  public:
  // string source = 4;
  void clear_source() ;
  const std::string& source() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_source(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_source();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_source();
  void set_allocated_source(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_source() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_source(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_source();

  public:
  // .internaledge.Job job = 1;
  bool has_job() const;
  void clear_job() ;
  const ::internaledge::Job& job() const;
  [[nodiscard]] ::internaledge::Job* PROTOBUF_NULLABLE release_job();
  ::internaledge::Job* PROTOBUF_NONNULL mutable_job();
  void set_allocated_job(::internaledge::Job* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_job(::internaledge::Job* PROTOBUF_NULLABLE value);
  ::internaledge::Job* PROTOBUF_NULLABLE unsafe_arena_release_job();

  private:
  const ::internaledge::Job& _internal_job() const;
  ::internaledge::Job* PROTOBUF_NONNULL _internal_mutable_job();

  public:
  // .google.protobuf.Timestamp timestamp = 3;
  bool has_timestamp() const;
  void clear_timestamp() ;
  const ::google::protobuf::Timestamp& timestamp() const;
  [[nodiscard]] ::google::protobuf::Timestamp* PROTOBUF_NULLABLE release_timestamp();
  ::google::protobuf::Timestamp* PROTOBUF_NONNULL mutable_timestamp();
  void set_allocated_timestamp(::google::protobuf::Timestamp* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_timestamp(::google::protobuf::Timestamp* PROTOBUF_NULLABLE value);
  ::google::protobuf::Timestamp* PROTOBUF_NULLABLE unsafe_arena_release_timestamp();

  private:
  const ::google::protobuf::Timestamp& _internal_timestamp() const;
  ::google::protobuf::Timestamp* PROTOBUF_NONNULL _internal_mutable_timestamp();

  public:
  // optional .internaledge.Location location = 5;
  bool has_location() const;
  void clear_location() ;
  const ::internaledge::Location& location() const;
  [[nodiscard]] ::internaledge::Location* PROTOBUF_NULLABLE release_location();
  ::internaledge::Location* PROTOBUF_NONNULL mutable_location();
  void set_allocated_location(::internaledge::Location* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_location(::internaledge::Location* PROTOBUF_NULLABLE value);
  ::internaledge::Location* PROTOBUF_NULLABLE unsafe_arena_release_location();

  private:
  const ::internaledge::Location& _internal_location() const;
  ::internaledge::Location* PROTOBUF_NONNULL _internal_mutable_location();

  public:
  // @@protoc_insertion_point(class_scope:internaledge.Scan)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   3, 40,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Scan& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr event_id_;
    ::google::protobuf::internal::ArenaStringPtr source_;
    ::internaledge::Job* PROTOBUF_NULLABLE job_;
    ::google::protobuf::Timestamp* PROTOBUF_NULLABLE timestamp_;
    ::internaledge::Location* PROTOBUF_NULLABLE location_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protos_2finternal_5fedge_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Scan_class_data_;
// -------------------------------------------------------------------

class ScanRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:internaledge.ScanRequest) */ {
 public:
  inline ScanRequest() : ScanRequest(nullptr) {}
  ~ScanRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ScanRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ScanRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ScanRequest(::google::protobuf::internal::ConstantInitialized);

  inline ScanRequest(const ScanRequest& from) : ScanRequest(nullptr, from) {}
  inline ScanRequest(ScanRequest&& from) noexcept
      : ScanRequest(nullptr, std::move(from)) {}
  inline ScanRequest& operator=(const ScanRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ScanRequest& operator=(ScanRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ScanRequest& default_instance() {
    return *reinterpret_cast<const ScanRequest*>(
        &_ScanRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(ScanRequest& a, ScanRequest& b) { a.Swap(&b); }
  inline void Swap(ScanRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ScanRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ScanRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ScanRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ScanRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ScanRequest& from) { ScanRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ScanRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "internaledge.ScanRequest"; }

 protected:
  explicit ScanRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ScanRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ScanRequest& from);
  ScanRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ScanRequest&& from) noexcept
      : ScanRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kScansFieldNumber = 1,
  };
  // repeated .internaledge.Scan scans = 1;
  int scans_size() const;
  private:
  int _internal_scans_size() const;

  public:
  void clear_scans() ;
  ::internaledge::Scan* PROTOBUF_NONNULL mutable_scans(int index);
  ::google::protobuf::RepeatedPtrField<::internaledge::Scan>* PROTOBUF_NONNULL mutable_scans();

  private:
  const ::google::protobuf::RepeatedPtrField<::internaledge::Scan>& _internal_scans() const;
  ::google::protobuf::RepeatedPtrField<::internaledge::Scan>* PROTOBUF_NONNULL _internal_mutable_scans();
  public:
  const ::internaledge::Scan& scans(int index) const;
  ::internaledge::Scan* PROTOBUF_NONNULL add_scans();
  const ::google::protobuf::RepeatedPtrField<::internaledge::Scan>& scans() const;
  // @@protoc_insertion_point(class_scope:internaledge.ScanRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ScanRequest& from_msg);
    ::google::protobuf::RepeatedPtrField< ::internaledge::Scan > scans_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protos_2finternal_5fedge_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ScanRequest_class_data_;
// -------------------------------------------------------------------

class ProcessingResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:internaledge.ProcessingResponse) */ {
 public:
  inline ProcessingResponse() : ProcessingResponse(nullptr) {}
  ~ProcessingResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ProcessingResponse* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ProcessingResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ProcessingResponse(::google::protobuf::internal::ConstantInitialized);

  inline ProcessingResponse(const ProcessingResponse& from) : ProcessingResponse(nullptr, from) {}
  inline ProcessingResponse(ProcessingResponse&& from) noexcept
      : ProcessingResponse(nullptr, std::move(from)) {}
  inline ProcessingResponse& operator=(const ProcessingResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProcessingResponse& operator=(ProcessingResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProcessingResponse& default_instance() {
    return *reinterpret_cast<const ProcessingResponse*>(
        &_ProcessingResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(ProcessingResponse& a, ProcessingResponse& b) { a.Swap(&b); }
  inline void Swap(ProcessingResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProcessingResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProcessingResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ProcessingResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ProcessingResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ProcessingResponse& from) { ProcessingResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ProcessingResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "internaledge.ProcessingResponse"; }

 protected:
  explicit ProcessingResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ProcessingResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ProcessingResponse& from);
  ProcessingResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ProcessingResponse&& from) noexcept
      : ProcessingResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Status = ProcessingResponse_Status;
  static constexpr Status SUCCESS = ProcessingResponse_Status_SUCCESS;
  static constexpr Status FAILURE = ProcessingResponse_Status_FAILURE;
  static constexpr Status PARTIAL_SUCCESS = ProcessingResponse_Status_PARTIAL_SUCCESS;
  static inline bool Status_IsValid(int value) {
    return ProcessingResponse_Status_IsValid(value);
  }
  static constexpr Status Status_MIN = ProcessingResponse_Status_Status_MIN;
  static constexpr Status Status_MAX = ProcessingResponse_Status_Status_MAX;
  static constexpr int Status_ARRAYSIZE = ProcessingResponse_Status_Status_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Status_descriptor() {
    return ProcessingResponse_Status_descriptor();
  }
  template <typename T>
  static inline const std::string& Status_Name(T value) {
    return ProcessingResponse_Status_Name(value);
  }
  static inline bool Status_Parse(
      absl::string_view name, Status* PROTOBUF_NONNULL value) {
    return ProcessingResponse_Status_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kSuccessfulScansFieldNumber = 3,
    kMessageFieldNumber = 2,
    kJobFieldNumber = 4,
    kStatusFieldNumber = 1,
  };
  // repeated .internaledge.Scan successful_scans = 3;
  int successful_scans_size() const;
  private:
  int _internal_successful_scans_size() const;

  public:
  void clear_successful_scans() ;
  ::internaledge::Scan* PROTOBUF_NONNULL mutable_successful_scans(int index);
  ::google::protobuf::RepeatedPtrField<::internaledge::Scan>* PROTOBUF_NONNULL mutable_successful_scans();

  private:
  const ::google::protobuf::RepeatedPtrField<::internaledge::Scan>& _internal_successful_scans() const;
  ::google::protobuf::RepeatedPtrField<::internaledge::Scan>* PROTOBUF_NONNULL _internal_mutable_successful_scans();
  public:
  const ::internaledge::Scan& successful_scans(int index) const;
  ::internaledge::Scan* PROTOBUF_NONNULL add_successful_scans();
  const ::google::protobuf::RepeatedPtrField<::internaledge::Scan>& successful_scans() const;
  // string message = 2;
  void clear_message() ;
  const std::string& message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_message();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_message();
  void set_allocated_message(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_message() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_message();

  public:
  // optional .internaledge.Job job = 4;
  bool has_job() const;
  void clear_job() ;
  const ::internaledge::Job& job() const;
  [[nodiscard]] ::internaledge::Job* PROTOBUF_NULLABLE release_job();
  ::internaledge::Job* PROTOBUF_NONNULL mutable_job();
  void set_allocated_job(::internaledge::Job* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_job(::internaledge::Job* PROTOBUF_NULLABLE value);
  ::internaledge::Job* PROTOBUF_NULLABLE unsafe_arena_release_job();

  private:
  const ::internaledge::Job& _internal_job() const;
  ::internaledge::Job* PROTOBUF_NONNULL _internal_mutable_job();

  public:
  // .internaledge.ProcessingResponse.Status status = 1;
  void clear_status() ;
  ::internaledge::ProcessingResponse_Status status() const;
  void set_status(::internaledge::ProcessingResponse_Status value);

  private:
  ::internaledge::ProcessingResponse_Status _internal_status() const;
  void _internal_set_status(::internaledge::ProcessingResponse_Status value);

  public:
  // @@protoc_insertion_point(class_scope:internaledge.ProcessingResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   2, 47,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ProcessingResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::internaledge::Scan > successful_scans_;
    ::google::protobuf::internal::ArenaStringPtr message_;
    ::internaledge::Job* PROTOBUF_NULLABLE job_;
    int status_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protos_2finternal_5fedge_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ProcessingResponse_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Job

// int64 job_id = 1;
inline void Job::clear_job_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.job_id_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int64_t Job::job_id() const {
  // @@protoc_insertion_point(field_get:internaledge.Job.job_id)
  return _internal_job_id();
}
inline void Job::set_job_id(::int64_t value) {
  _internal_set_job_id(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:internaledge.Job.job_id)
}
inline ::int64_t Job::_internal_job_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.job_id_;
}
inline void Job::_internal_set_job_id(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.job_id_ = value;
}

// -------------------------------------------------------------------

// Scan

// .internaledge.Job job = 1;
inline bool Scan::has_job() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.job_ != nullptr);
  return value;
}
inline void Scan::clear_job() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.job_ != nullptr) _impl_.job_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const ::internaledge::Job& Scan::_internal_job() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::internaledge::Job* p = _impl_.job_;
  return p != nullptr ? *p : reinterpret_cast<const ::internaledge::Job&>(::internaledge::_Job_default_instance_);
}
inline const ::internaledge::Job& Scan::job() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:internaledge.Scan.job)
  return _internal_job();
}
inline void Scan::unsafe_arena_set_allocated_job(
    ::internaledge::Job* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.job_);
  }
  _impl_.job_ = reinterpret_cast<::internaledge::Job*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:internaledge.Scan.job)
}
inline ::internaledge::Job* PROTOBUF_NULLABLE Scan::release_job() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::internaledge::Job* released = _impl_.job_;
  _impl_.job_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::internaledge::Job* PROTOBUF_NULLABLE Scan::unsafe_arena_release_job() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:internaledge.Scan.job)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::internaledge::Job* temp = _impl_.job_;
  _impl_.job_ = nullptr;
  return temp;
}
inline ::internaledge::Job* PROTOBUF_NONNULL Scan::_internal_mutable_job() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.job_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::internaledge::Job>(GetArena());
    _impl_.job_ = reinterpret_cast<::internaledge::Job*>(p);
  }
  return _impl_.job_;
}
inline ::internaledge::Job* PROTOBUF_NONNULL Scan::mutable_job()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004u;
  ::internaledge::Job* _msg = _internal_mutable_job();
  // @@protoc_insertion_point(field_mutable:internaledge.Scan.job)
  return _msg;
}
inline void Scan::set_allocated_job(::internaledge::Job* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.job_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.job_ = reinterpret_cast<::internaledge::Job*>(value);
  // @@protoc_insertion_point(field_set_allocated:internaledge.Scan.job)
}

// string event_id = 2;
inline void Scan::clear_event_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.event_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Scan::event_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:internaledge.Scan.event_id)
  return _internal_event_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Scan::set_event_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.event_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:internaledge.Scan.event_id)
}
inline std::string* PROTOBUF_NONNULL Scan::mutable_event_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_event_id();
  // @@protoc_insertion_point(field_mutable:internaledge.Scan.event_id)
  return _s;
}
inline const std::string& Scan::_internal_event_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.event_id_.Get();
}
inline void Scan::_internal_set_event_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.event_id_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL Scan::_internal_mutable_event_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.event_id_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE Scan::release_event_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:internaledge.Scan.event_id)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.event_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.event_id_.Set("", GetArena());
  }
  return released;
}
inline void Scan::set_allocated_event_id(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.event_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.event_id_.IsDefault()) {
    _impl_.event_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:internaledge.Scan.event_id)
}

// .google.protobuf.Timestamp timestamp = 3;
inline bool Scan::has_timestamp() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.timestamp_ != nullptr);
  return value;
}
inline const ::google::protobuf::Timestamp& Scan::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::google::protobuf::Timestamp* p = _impl_.timestamp_;
  return p != nullptr ? *p : reinterpret_cast<const ::google::protobuf::Timestamp&>(::google::protobuf::_Timestamp_default_instance_);
}
inline const ::google::protobuf::Timestamp& Scan::timestamp() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:internaledge.Scan.timestamp)
  return _internal_timestamp();
}
inline void Scan::unsafe_arena_set_allocated_timestamp(
    ::google::protobuf::Timestamp* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.timestamp_);
  }
  _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:internaledge.Scan.timestamp)
}
inline ::google::protobuf::Timestamp* PROTOBUF_NULLABLE Scan::release_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::google::protobuf::Timestamp* released = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::google::protobuf::Timestamp* PROTOBUF_NULLABLE Scan::unsafe_arena_release_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:internaledge.Scan.timestamp)

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::google::protobuf::Timestamp* temp = _impl_.timestamp_;
  _impl_.timestamp_ = nullptr;
  return temp;
}
inline ::google::protobuf::Timestamp* PROTOBUF_NONNULL Scan::_internal_mutable_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.timestamp_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::google::protobuf::Timestamp>(GetArena());
    _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(p);
  }
  return _impl_.timestamp_;
}
inline ::google::protobuf::Timestamp* PROTOBUF_NONNULL Scan::mutable_timestamp()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000008u;
  ::google::protobuf::Timestamp* _msg = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:internaledge.Scan.timestamp)
  return _msg;
}
inline void Scan::set_allocated_timestamp(::google::protobuf::Timestamp* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.timestamp_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::Message*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }

  _impl_.timestamp_ = reinterpret_cast<::google::protobuf::Timestamp*>(value);
  // @@protoc_insertion_point(field_set_allocated:internaledge.Scan.timestamp)
}

// string source = 4;
inline void Scan::clear_source() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Scan::source() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:internaledge.Scan.source)
  return _internal_source();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Scan::set_source(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.source_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:internaledge.Scan.source)
}
inline std::string* PROTOBUF_NONNULL Scan::mutable_source()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_source();
  // @@protoc_insertion_point(field_mutable:internaledge.Scan.source)
  return _s;
}
inline const std::string& Scan::_internal_source() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.source_.Get();
}
inline void Scan::_internal_set_source(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.source_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL Scan::_internal_mutable_source() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.source_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE Scan::release_source() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:internaledge.Scan.source)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.source_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.source_.Set("", GetArena());
  }
  return released;
}
inline void Scan::set_allocated_source(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.source_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.source_.IsDefault()) {
    _impl_.source_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:internaledge.Scan.source)
}

// optional .internaledge.Location location = 5;
inline bool Scan::has_location() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.location_ != nullptr);
  return value;
}
inline void Scan::clear_location() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.location_ != nullptr) _impl_.location_->Clear();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline const ::internaledge::Location& Scan::_internal_location() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::internaledge::Location* p = _impl_.location_;
  return p != nullptr ? *p : reinterpret_cast<const ::internaledge::Location&>(::internaledge::_Location_default_instance_);
}
inline const ::internaledge::Location& Scan::location() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:internaledge.Scan.location)
  return _internal_location();
}
inline void Scan::unsafe_arena_set_allocated_location(
    ::internaledge::Location* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.location_);
  }
  _impl_.location_ = reinterpret_cast<::internaledge::Location*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:internaledge.Scan.location)
}
inline ::internaledge::Location* PROTOBUF_NULLABLE Scan::release_location() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000010u;
  ::internaledge::Location* released = _impl_.location_;
  _impl_.location_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::internaledge::Location* PROTOBUF_NULLABLE Scan::unsafe_arena_release_location() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:internaledge.Scan.location)

  _impl_._has_bits_[0] &= ~0x00000010u;
  ::internaledge::Location* temp = _impl_.location_;
  _impl_.location_ = nullptr;
  return temp;
}
inline ::internaledge::Location* PROTOBUF_NONNULL Scan::_internal_mutable_location() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.location_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::internaledge::Location>(GetArena());
    _impl_.location_ = reinterpret_cast<::internaledge::Location*>(p);
  }
  return _impl_.location_;
}
inline ::internaledge::Location* PROTOBUF_NONNULL Scan::mutable_location()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000010u;
  ::internaledge::Location* _msg = _internal_mutable_location();
  // @@protoc_insertion_point(field_mutable:internaledge.Scan.location)
  return _msg;
}
inline void Scan::set_allocated_location(::internaledge::Location* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.location_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }

  _impl_.location_ = reinterpret_cast<::internaledge::Location*>(value);
  // @@protoc_insertion_point(field_set_allocated:internaledge.Scan.location)
}

// -------------------------------------------------------------------

// Location

// double latitude = 1;
inline void Location::clear_latitude() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.latitude_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline double Location::latitude() const {
  // @@protoc_insertion_point(field_get:internaledge.Location.latitude)
  return _internal_latitude();
}
inline void Location::set_latitude(double value) {
  _internal_set_latitude(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:internaledge.Location.latitude)
}
inline double Location::_internal_latitude() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.latitude_;
}
inline void Location::_internal_set_latitude(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.latitude_ = value;
}

// double longitude = 2;
inline void Location::clear_longitude() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.longitude_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline double Location::longitude() const {
  // @@protoc_insertion_point(field_get:internaledge.Location.longitude)
  return _internal_longitude();
}
inline void Location::set_longitude(double value) {
  _internal_set_longitude(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:internaledge.Location.longitude)
}
inline double Location::_internal_longitude() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.longitude_;
}
inline void Location::_internal_set_longitude(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.longitude_ = value;
}

// optional double altitude = 3;
inline bool Location::has_altitude() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void Location::clear_altitude() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.altitude_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline double Location::altitude() const {
  // @@protoc_insertion_point(field_get:internaledge.Location.altitude)
  return _internal_altitude();
}
inline void Location::set_altitude(double value) {
  _internal_set_altitude(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:internaledge.Location.altitude)
}
inline double Location::_internal_altitude() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.altitude_;
}
inline void Location::_internal_set_altitude(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.altitude_ = value;
}

// -------------------------------------------------------------------

// ScanRequest

// repeated .internaledge.Scan scans = 1;
inline int ScanRequest::_internal_scans_size() const {
  return _internal_scans().size();
}
inline int ScanRequest::scans_size() const {
  return _internal_scans_size();
}
inline void ScanRequest::clear_scans() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.scans_.Clear();
}
inline ::internaledge::Scan* PROTOBUF_NONNULL ScanRequest::mutable_scans(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:internaledge.ScanRequest.scans)
  return _internal_mutable_scans()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::internaledge::Scan>* PROTOBUF_NONNULL ScanRequest::mutable_scans()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:internaledge.ScanRequest.scans)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_scans();
}
inline const ::internaledge::Scan& ScanRequest::scans(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:internaledge.ScanRequest.scans)
  return _internal_scans().Get(index);
}
inline ::internaledge::Scan* PROTOBUF_NONNULL ScanRequest::add_scans()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::internaledge::Scan* _add = _internal_mutable_scans()->Add();
  // @@protoc_insertion_point(field_add:internaledge.ScanRequest.scans)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::internaledge::Scan>& ScanRequest::scans() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:internaledge.ScanRequest.scans)
  return _internal_scans();
}
inline const ::google::protobuf::RepeatedPtrField<::internaledge::Scan>&
ScanRequest::_internal_scans() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.scans_;
}
inline ::google::protobuf::RepeatedPtrField<::internaledge::Scan>* PROTOBUF_NONNULL
ScanRequest::_internal_mutable_scans() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.scans_;
}

// -------------------------------------------------------------------

// ProcessingResponse

// .internaledge.ProcessingResponse.Status status = 1;
inline void ProcessingResponse::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::internaledge::ProcessingResponse_Status ProcessingResponse::status() const {
  // @@protoc_insertion_point(field_get:internaledge.ProcessingResponse.status)
  return _internal_status();
}
inline void ProcessingResponse::set_status(::internaledge::ProcessingResponse_Status value) {
  _internal_set_status(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:internaledge.ProcessingResponse.status)
}
inline ::internaledge::ProcessingResponse_Status ProcessingResponse::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::internaledge::ProcessingResponse_Status>(_impl_.status_);
}
inline void ProcessingResponse::_internal_set_status(::internaledge::ProcessingResponse_Status value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// string message = 2;
inline void ProcessingResponse::clear_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ProcessingResponse::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:internaledge.ProcessingResponse.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ProcessingResponse::set_message(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:internaledge.ProcessingResponse.message)
}
inline std::string* PROTOBUF_NONNULL ProcessingResponse::mutable_message()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:internaledge.ProcessingResponse.message)
  return _s;
}
inline const std::string& ProcessingResponse::_internal_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_.Get();
}
inline void ProcessingResponse::_internal_set_message(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.message_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL ProcessingResponse::_internal_mutable_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.message_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE ProcessingResponse::release_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:internaledge.ProcessingResponse.message)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.message_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.message_.Set("", GetArena());
  }
  return released;
}
inline void ProcessingResponse::set_allocated_message(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:internaledge.ProcessingResponse.message)
}

// repeated .internaledge.Scan successful_scans = 3;
inline int ProcessingResponse::_internal_successful_scans_size() const {
  return _internal_successful_scans().size();
}
inline int ProcessingResponse::successful_scans_size() const {
  return _internal_successful_scans_size();
}
inline void ProcessingResponse::clear_successful_scans() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.successful_scans_.Clear();
}
inline ::internaledge::Scan* PROTOBUF_NONNULL ProcessingResponse::mutable_successful_scans(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:internaledge.ProcessingResponse.successful_scans)
  return _internal_mutable_successful_scans()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::internaledge::Scan>* PROTOBUF_NONNULL ProcessingResponse::mutable_successful_scans()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:internaledge.ProcessingResponse.successful_scans)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_successful_scans();
}
inline const ::internaledge::Scan& ProcessingResponse::successful_scans(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:internaledge.ProcessingResponse.successful_scans)
  return _internal_successful_scans().Get(index);
}
inline ::internaledge::Scan* PROTOBUF_NONNULL ProcessingResponse::add_successful_scans()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::internaledge::Scan* _add = _internal_mutable_successful_scans()->Add();
  // @@protoc_insertion_point(field_add:internaledge.ProcessingResponse.successful_scans)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::internaledge::Scan>& ProcessingResponse::successful_scans() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:internaledge.ProcessingResponse.successful_scans)
  return _internal_successful_scans();
}
inline const ::google::protobuf::RepeatedPtrField<::internaledge::Scan>&
ProcessingResponse::_internal_successful_scans() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.successful_scans_;
}
inline ::google::protobuf::RepeatedPtrField<::internaledge::Scan>* PROTOBUF_NONNULL
ProcessingResponse::_internal_mutable_successful_scans() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.successful_scans_;
}

// optional .internaledge.Job job = 4;
inline bool ProcessingResponse::has_job() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.job_ != nullptr);
  return value;
}
inline void ProcessingResponse::clear_job() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.job_ != nullptr) _impl_.job_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::internaledge::Job& ProcessingResponse::_internal_job() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::internaledge::Job* p = _impl_.job_;
  return p != nullptr ? *p : reinterpret_cast<const ::internaledge::Job&>(::internaledge::_Job_default_instance_);
}
inline const ::internaledge::Job& ProcessingResponse::job() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:internaledge.ProcessingResponse.job)
  return _internal_job();
}
inline void ProcessingResponse::unsafe_arena_set_allocated_job(
    ::internaledge::Job* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.job_);
  }
  _impl_.job_ = reinterpret_cast<::internaledge::Job*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:internaledge.ProcessingResponse.job)
}
inline ::internaledge::Job* PROTOBUF_NULLABLE ProcessingResponse::release_job() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::internaledge::Job* released = _impl_.job_;
  _impl_.job_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::internaledge::Job* PROTOBUF_NULLABLE ProcessingResponse::unsafe_arena_release_job() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:internaledge.ProcessingResponse.job)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::internaledge::Job* temp = _impl_.job_;
  _impl_.job_ = nullptr;
  return temp;
}
inline ::internaledge::Job* PROTOBUF_NONNULL ProcessingResponse::_internal_mutable_job() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.job_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::internaledge::Job>(GetArena());
    _impl_.job_ = reinterpret_cast<::internaledge::Job*>(p);
  }
  return _impl_.job_;
}
inline ::internaledge::Job* PROTOBUF_NONNULL ProcessingResponse::mutable_job()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::internaledge::Job* _msg = _internal_mutable_job();
  // @@protoc_insertion_point(field_mutable:internaledge.ProcessingResponse.job)
  return _msg;
}
inline void ProcessingResponse::set_allocated_job(::internaledge::Job* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.job_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.job_ = reinterpret_cast<::internaledge::Job*>(value);
  // @@protoc_insertion_point(field_set_allocated:internaledge.ProcessingResponse.job)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace internaledge


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::internaledge::ProcessingResponse_Status> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::internaledge::ProcessingResponse_Status>() {
  return ::internaledge::ProcessingResponse_Status_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // protos_2finternal_5fedge_2eproto_2epb_2eh
