// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos/internal_edge.proto
// Protobuf C++ Version: 6.30.2

#include "protos/internal_edge.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace internaledge {

inline constexpr Location::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        latitude_{0},
        longitude_{0},
        altitude_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Location::Location(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Location_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct LocationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LocationDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LocationDefaultTypeInternal() {}
  union {
    Location _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LocationDefaultTypeInternal _Location_default_instance_;

inline constexpr Job::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        job_id_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR Job::Job(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Job_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct JobDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JobDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~JobDefaultTypeInternal() {}
  union {
    Job _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JobDefaultTypeInternal _Job_default_instance_;

inline constexpr Scan::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        event_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        source_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        job_{nullptr},
        timestamp_{nullptr},
        location_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR Scan::Scan(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Scan_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ScanDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ScanDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ScanDefaultTypeInternal() {}
  union {
    Scan _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ScanDefaultTypeInternal _Scan_default_instance_;

inline constexpr ScanRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : scans_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ScanRequest::ScanRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ScanRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ScanRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ScanRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ScanRequestDefaultTypeInternal() {}
  union {
    ScanRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ScanRequestDefaultTypeInternal _ScanRequest_default_instance_;

inline constexpr ProcessingResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        successful_scans_{},
        message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        job_{nullptr},
        status_{static_cast< ::internaledge::ProcessingResponse_Status >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR ProcessingResponse::ProcessingResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ProcessingResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ProcessingResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProcessingResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProcessingResponseDefaultTypeInternal() {}
  union {
    ProcessingResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProcessingResponseDefaultTypeInternal _ProcessingResponse_default_instance_;
}  // namespace internaledge
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_protos_2finternal_5fedge_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_protos_2finternal_5fedge_2eproto = nullptr;
const ::uint32_t
    TableStruct_protos_2finternal_5fedge_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::internaledge::Job, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::internaledge::Job, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::internaledge::Job, _impl_.job_id_),
        0,
        PROTOBUF_FIELD_OFFSET(::internaledge::Scan, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::internaledge::Scan, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::internaledge::Scan, _impl_.job_),
        PROTOBUF_FIELD_OFFSET(::internaledge::Scan, _impl_.event_id_),
        PROTOBUF_FIELD_OFFSET(::internaledge::Scan, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::internaledge::Scan, _impl_.source_),
        PROTOBUF_FIELD_OFFSET(::internaledge::Scan, _impl_.location_),
        2,
        0,
        3,
        1,
        4,
        PROTOBUF_FIELD_OFFSET(::internaledge::Location, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::internaledge::Location, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::internaledge::Location, _impl_.latitude_),
        PROTOBUF_FIELD_OFFSET(::internaledge::Location, _impl_.longitude_),
        PROTOBUF_FIELD_OFFSET(::internaledge::Location, _impl_.altitude_),
        0,
        1,
        2,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::internaledge::ScanRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::internaledge::ScanRequest, _impl_.scans_),
        PROTOBUF_FIELD_OFFSET(::internaledge::ProcessingResponse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::internaledge::ProcessingResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::internaledge::ProcessingResponse, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::internaledge::ProcessingResponse, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::internaledge::ProcessingResponse, _impl_.successful_scans_),
        PROTOBUF_FIELD_OFFSET(::internaledge::ProcessingResponse, _impl_.job_),
        2,
        0,
        ~0u,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 9, -1, sizeof(::internaledge::Job)},
        {10, 23, -1, sizeof(::internaledge::Scan)},
        {28, 39, -1, sizeof(::internaledge::Location)},
        {42, -1, -1, sizeof(::internaledge::ScanRequest)},
        {51, 63, -1, sizeof(::internaledge::ProcessingResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::internaledge::_Job_default_instance_._instance,
    &::internaledge::_Scan_default_instance_._instance,
    &::internaledge::_Location_default_instance_._instance,
    &::internaledge::_ScanRequest_default_instance_._instance,
    &::internaledge::_ProcessingResponse_default_instance_._instance,
};
const char descriptor_table_protodef_protos_2finternal_5fedge_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\032protos/internal_edge.proto\022\014internaled"
    "ge\032\037google/protobuf/timestamp.proto\"\025\n\003J"
    "ob\022\016\n\006job_id\030\001 \001(\003\"\263\001\n\004Scan\022\036\n\003job\030\001 \001(\013"
    "2\021.internaledge.Job\022\020\n\010event_id\030\002 \001(\t\022-\n"
    "\ttimestamp\030\003 \001(\0132\032.google.protobuf.Times"
    "tamp\022\016\n\006source\030\004 \001(\t\022-\n\010location\030\005 \001(\0132\026"
    ".internaledge.LocationH\000\210\001\001B\013\n\t_location"
    "\"S\n\010Location\022\020\n\010latitude\030\001 \001(\001\022\021\n\tlongit"
    "ude\030\002 \001(\001\022\025\n\010altitude\030\003 \001(\001H\000\210\001\001B\013\n\t_alt"
    "itude\"0\n\013ScanRequest\022!\n\005scans\030\001 \003(\0132\022.in"
    "ternaledge.Scan\"\362\001\n\022ProcessingResponse\0227"
    "\n\006status\030\001 \001(\0162\'.internaledge.Processing"
    "Response.Status\022\017\n\007message\030\002 \001(\t\022,\n\020succ"
    "essful_scans\030\003 \003(\0132\022.internaledge.Scan\022#"
    "\n\003job\030\004 \001(\0132\021.internaledge.JobH\000\210\001\001\"7\n\006S"
    "tatus\022\013\n\007SUCCESS\020\000\022\013\n\007FAILURE\020\001\022\023\n\017PARTI"
    "AL_SUCCESS\020\002B\006\n\004_job2\214\001\n\rEdgeConnector\022."
    "\n\006GetJob\022\021.internaledge.Job\032\021.internaled"
    "ge.Job\022K\n\014ProcessScans\022\031.internaledge.Sc"
    "anRequest\032 .internaledge.ProcessingRespo"
    "nseb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_protos_2finternal_5fedge_2eproto_deps[1] = {
        &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::absl::once_flag descriptor_table_protos_2finternal_5fedge_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_protos_2finternal_5fedge_2eproto = {
    false,
    false,
    811,
    descriptor_table_protodef_protos_2finternal_5fedge_2eproto,
    "protos/internal_edge.proto",
    &descriptor_table_protos_2finternal_5fedge_2eproto_once,
    descriptor_table_protos_2finternal_5fedge_2eproto_deps,
    1,
    5,
    schemas,
    file_default_instances,
    TableStruct_protos_2finternal_5fedge_2eproto::offsets,
    file_level_enum_descriptors_protos_2finternal_5fedge_2eproto,
    file_level_service_descriptors_protos_2finternal_5fedge_2eproto,
};
namespace internaledge {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ProcessingResponse_Status_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_protos_2finternal_5fedge_2eproto);
  return file_level_enum_descriptors_protos_2finternal_5fedge_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ProcessingResponse_Status_internal_data_[] = {
    196608u, 0u, };
// ===================================================================

class Job::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Job>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Job, _impl_._has_bits_);
};

Job::Job(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Job_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:internaledge.Job)
}
Job::Job(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Job& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Job_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE Job::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Job::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.job_id_ = {};
}
Job::~Job() {
  // @@protoc_insertion_point(destructor:internaledge.Job)
  SharedDtor(*this);
}
inline void Job::SharedDtor(MessageLite& self) {
  Job& this_ = static_cast<Job&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Job::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Job(arena);
}
constexpr auto Job::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Job),
                                            alignof(Job));
}
constexpr auto Job::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Job_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Job::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Job>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Job::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Job>(), &Job::ByteSizeLong,
              &Job::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Job, _impl_._cached_size_),
          false,
      },
      &Job::kDescriptorMethods,
      &descriptor_table_protos_2finternal_5fedge_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Job_class_data_ =
        Job::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL Job::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Job_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Job_class_data_.tc_table);
  return Job_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
Job::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Job, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Job_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::internaledge::Job>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 job_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Job, _impl_.job_id_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(Job, _impl_.job_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 job_id = 1;
    {PROTOBUF_FIELD_OFFSET(Job, _impl_.job_id_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Job::Clear() {
// @@protoc_insertion_point(message_clear_start:internaledge.Job)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.job_id_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Job::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Job& this_ = static_cast<const Job&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Job::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Job& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:internaledge.Job)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 job_id = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_job_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
              stream, this_._internal_job_id(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:internaledge.Job)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Job::ByteSizeLong(const MessageLite& base) {
  const Job& this_ = static_cast<const Job&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Job::ByteSizeLong() const {
  const Job& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:internaledge.Job)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int64 job_id = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_job_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_job_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Job::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Job*>(&to_msg);
  auto& from = static_cast<const Job&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:internaledge.Job)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (from._internal_job_id() != 0) {
      _this->_impl_.job_id_ = from._impl_.job_id_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Job::CopyFrom(const Job& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:internaledge.Job)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Job::InternalSwap(Job* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.job_id_, other->_impl_.job_id_);
}

::google::protobuf::Metadata Job::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Scan::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Scan>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Scan, _impl_._has_bits_);
};

void Scan::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.timestamp_ != nullptr) _impl_.timestamp_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
Scan::Scan(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Scan_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:internaledge.Scan)
}
PROTOBUF_NDEBUG_INLINE Scan::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::internaledge::Scan& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        event_id_(arena, from.event_id_),
        source_(arena, from.source_) {}

Scan::Scan(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Scan& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Scan_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Scan* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.job_ = ((cached_has_bits & 0x00000004u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.job_)
                : nullptr;
  _impl_.timestamp_ = ((cached_has_bits & 0x00000008u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.timestamp_)
                : nullptr;
  _impl_.location_ = ((cached_has_bits & 0x00000010u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.location_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:internaledge.Scan)
}
PROTOBUF_NDEBUG_INLINE Scan::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        event_id_(arena),
        source_(arena) {}

inline void Scan::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, job_),
           0,
           offsetof(Impl_, location_) -
               offsetof(Impl_, job_) +
               sizeof(Impl_::location_));
}
Scan::~Scan() {
  // @@protoc_insertion_point(destructor:internaledge.Scan)
  SharedDtor(*this);
}
inline void Scan::SharedDtor(MessageLite& self) {
  Scan& this_ = static_cast<Scan&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.event_id_.Destroy();
  this_._impl_.source_.Destroy();
  delete this_._impl_.job_;
  delete this_._impl_.timestamp_;
  delete this_._impl_.location_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Scan::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Scan(arena);
}
constexpr auto Scan::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Scan),
                                            alignof(Scan));
}
constexpr auto Scan::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Scan_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Scan::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Scan>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Scan::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Scan>(), &Scan::ByteSizeLong,
              &Scan::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Scan, _impl_._cached_size_),
          false,
      },
      &Scan::kDescriptorMethods,
      &descriptor_table_protos_2finternal_5fedge_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Scan_class_data_ =
        Scan::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL Scan::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Scan_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Scan_class_data_.tc_table);
  return Scan_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 3, 40, 2>
Scan::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Scan, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Scan_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::internaledge::Scan>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .internaledge.Job job = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 2, 0, PROTOBUF_FIELD_OFFSET(Scan, _impl_.job_)}},
    // string event_id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(Scan, _impl_.event_id_)}},
    // .google.protobuf.Timestamp timestamp = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 3, 1, PROTOBUF_FIELD_OFFSET(Scan, _impl_.timestamp_)}},
    // string source = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 1, 0, PROTOBUF_FIELD_OFFSET(Scan, _impl_.source_)}},
    // optional .internaledge.Location location = 5;
    {::_pbi::TcParser::FastMtS1,
     {42, 4, 2, PROTOBUF_FIELD_OFFSET(Scan, _impl_.location_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .internaledge.Job job = 1;
    {PROTOBUF_FIELD_OFFSET(Scan, _impl_.job_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string event_id = 2;
    {PROTOBUF_FIELD_OFFSET(Scan, _impl_.event_id_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .google.protobuf.Timestamp timestamp = 3;
    {PROTOBUF_FIELD_OFFSET(Scan, _impl_.timestamp_), _Internal::kHasBitsOffset + 3, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string source = 4;
    {PROTOBUF_FIELD_OFFSET(Scan, _impl_.source_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional .internaledge.Location location = 5;
    {PROTOBUF_FIELD_OFFSET(Scan, _impl_.location_), _Internal::kHasBitsOffset + 4, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::internaledge::Job>()},
      {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
      {::_pbi::TcParser::GetTable<::internaledge::Location>()},
  }},
  {{
    "\21\0\10\0\6\0\0\0"
    "internaledge.Scan"
    "event_id"
    "source"
  }},
};
PROTOBUF_NOINLINE void Scan::Clear() {
// @@protoc_insertion_point(message_clear_start:internaledge.Scan)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.event_id_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.source_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      ABSL_DCHECK(_impl_.job_ != nullptr);
      _impl_.job_->Clear();
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      ABSL_DCHECK(_impl_.timestamp_ != nullptr);
      _impl_.timestamp_->Clear();
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      ABSL_DCHECK(_impl_.location_ != nullptr);
      _impl_.location_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Scan::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Scan& this_ = static_cast<const Scan&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Scan::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Scan& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:internaledge.Scan)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .internaledge.Job job = 1;
  if ((cached_has_bits & 0x00000004u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.job_, this_._impl_.job_->GetCachedSize(), target,
        stream);
  }

  // string event_id = 2;
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!this_._internal_event_id().empty()) {
      const std::string& _s = this_._internal_event_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "internaledge.Scan.event_id");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // .google.protobuf.Timestamp timestamp = 3;
  if ((cached_has_bits & 0x00000008u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.timestamp_, this_._impl_.timestamp_->GetCachedSize(), target,
        stream);
  }

  // string source = 4;
  if ((cached_has_bits & 0x00000002u) != 0) {
    if (!this_._internal_source().empty()) {
      const std::string& _s = this_._internal_source();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "internaledge.Scan.source");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  // optional .internaledge.Location location = 5;
  if ((cached_has_bits & 0x00000010u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        5, *this_._impl_.location_, this_._impl_.location_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:internaledge.Scan)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Scan::ByteSizeLong(const MessageLite& base) {
  const Scan& this_ = static_cast<const Scan&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Scan::ByteSizeLong() const {
  const Scan& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:internaledge.Scan)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    // string event_id = 2;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_event_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_event_id());
      }
    }
    // string source = 4;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!this_._internal_source().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_source());
      }
    }
    // .internaledge.Job job = 1;
    if ((cached_has_bits & 0x00000004u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.job_);
    }
    // .google.protobuf.Timestamp timestamp = 3;
    if ((cached_has_bits & 0x00000008u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.timestamp_);
    }
    // optional .internaledge.Location location = 5;
    if ((cached_has_bits & 0x00000010u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.location_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Scan::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Scan*>(&to_msg);
  auto& from = static_cast<const Scan&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:internaledge.Scan)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_event_id().empty()) {
        _this->_internal_set_event_id(from._internal_event_id());
      } else {
        if (_this->_impl_.event_id_.IsDefault()) {
          _this->_internal_set_event_id("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!from._internal_source().empty()) {
        _this->_internal_set_source(from._internal_source());
      } else {
        if (_this->_impl_.source_.IsDefault()) {
          _this->_internal_set_source("");
        }
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      ABSL_DCHECK(from._impl_.job_ != nullptr);
      if (_this->_impl_.job_ == nullptr) {
        _this->_impl_.job_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.job_);
      } else {
        _this->_impl_.job_->MergeFrom(*from._impl_.job_);
      }
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      ABSL_DCHECK(from._impl_.timestamp_ != nullptr);
      if (_this->_impl_.timestamp_ == nullptr) {
        _this->_impl_.timestamp_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.timestamp_);
      } else {
        _this->_impl_.timestamp_->MergeFrom(*from._impl_.timestamp_);
      }
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      ABSL_DCHECK(from._impl_.location_ != nullptr);
      if (_this->_impl_.location_ == nullptr) {
        _this->_impl_.location_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.location_);
      } else {
        _this->_impl_.location_->MergeFrom(*from._impl_.location_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Scan::CopyFrom(const Scan& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:internaledge.Scan)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Scan::InternalSwap(Scan* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.event_id_, &other->_impl_.event_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.source_, &other->_impl_.source_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Scan, _impl_.location_)
      + sizeof(Scan::_impl_.location_)
      - PROTOBUF_FIELD_OFFSET(Scan, _impl_.job_)>(
          reinterpret_cast<char*>(&_impl_.job_),
          reinterpret_cast<char*>(&other->_impl_.job_));
}

::google::protobuf::Metadata Scan::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Location::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Location>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Location, _impl_._has_bits_);
};

Location::Location(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Location_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:internaledge.Location)
}
Location::Location(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Location& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Location_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE Location::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Location::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, latitude_),
           0,
           offsetof(Impl_, altitude_) -
               offsetof(Impl_, latitude_) +
               sizeof(Impl_::altitude_));
}
Location::~Location() {
  // @@protoc_insertion_point(destructor:internaledge.Location)
  SharedDtor(*this);
}
inline void Location::SharedDtor(MessageLite& self) {
  Location& this_ = static_cast<Location&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Location::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Location(arena);
}
constexpr auto Location::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Location),
                                            alignof(Location));
}
constexpr auto Location::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Location_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Location::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Location>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Location::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Location>(), &Location::ByteSizeLong,
              &Location::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Location, _impl_._cached_size_),
          false,
      },
      &Location::kDescriptorMethods,
      &descriptor_table_protos_2finternal_5fedge_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Location_class_data_ =
        Location::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL Location::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Location_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Location_class_data_.tc_table);
  return Location_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
Location::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Location, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Location_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::internaledge::Location>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // double latitude = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 0, 0, PROTOBUF_FIELD_OFFSET(Location, _impl_.latitude_)}},
    // double longitude = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 1, 0, PROTOBUF_FIELD_OFFSET(Location, _impl_.longitude_)}},
    // optional double altitude = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 2, 0, PROTOBUF_FIELD_OFFSET(Location, _impl_.altitude_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double latitude = 1;
    {PROTOBUF_FIELD_OFFSET(Location, _impl_.latitude_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double longitude = 2;
    {PROTOBUF_FIELD_OFFSET(Location, _impl_.longitude_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // optional double altitude = 3;
    {PROTOBUF_FIELD_OFFSET(Location, _impl_.altitude_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Location::Clear() {
// @@protoc_insertion_point(message_clear_start:internaledge.Location)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    ::memset(&_impl_.latitude_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.altitude_) -
        reinterpret_cast<char*>(&_impl_.latitude_)) + sizeof(_impl_.altitude_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Location::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Location& this_ = static_cast<const Location&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Location::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Location& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:internaledge.Location)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // double latitude = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_latitude()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          1, this_._internal_latitude(), target);
    }
  }

  // double longitude = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_longitude()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          2, this_._internal_longitude(), target);
    }
  }

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional double altitude = 3;
  if ((cached_has_bits & 0x00000004u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        3, this_._internal_altitude(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:internaledge.Location)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Location::ByteSizeLong(const MessageLite& base) {
  const Location& this_ = static_cast<const Location&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Location::ByteSizeLong() const {
  const Location& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:internaledge.Location)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000004u & cached_has_bits) * 9;
  if ((cached_has_bits & 0x00000003u) != 0) {
    // double latitude = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_latitude()) != 0) {
        total_size += 9;
      }
    }
    // double longitude = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_longitude()) != 0) {
        total_size += 9;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Location::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Location*>(&to_msg);
  auto& from = static_cast<const Location&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:internaledge.Location)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (::absl::bit_cast<::uint64_t>(from._internal_latitude()) != 0) {
        _this->_impl_.latitude_ = from._impl_.latitude_;
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (::absl::bit_cast<::uint64_t>(from._internal_longitude()) != 0) {
        _this->_impl_.longitude_ = from._impl_.longitude_;
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _this->_impl_.altitude_ = from._impl_.altitude_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Location::CopyFrom(const Location& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:internaledge.Location)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Location::InternalSwap(Location* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Location, _impl_.altitude_)
      + sizeof(Location::_impl_.altitude_)
      - PROTOBUF_FIELD_OFFSET(Location, _impl_.latitude_)>(
          reinterpret_cast<char*>(&_impl_.latitude_),
          reinterpret_cast<char*>(&other->_impl_.latitude_));
}

::google::protobuf::Metadata Location::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ScanRequest::_Internal {
 public:
};

ScanRequest::ScanRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ScanRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:internaledge.ScanRequest)
}
PROTOBUF_NDEBUG_INLINE ScanRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::internaledge::ScanRequest& from_msg)
      : scans_{visibility, arena, from.scans_},
        _cached_size_{0} {}

ScanRequest::ScanRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ScanRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ScanRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ScanRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:internaledge.ScanRequest)
}
PROTOBUF_NDEBUG_INLINE ScanRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : scans_{visibility, arena},
        _cached_size_{0} {}

inline void ScanRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ScanRequest::~ScanRequest() {
  // @@protoc_insertion_point(destructor:internaledge.ScanRequest)
  SharedDtor(*this);
}
inline void ScanRequest::SharedDtor(MessageLite& self) {
  ScanRequest& this_ = static_cast<ScanRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ScanRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ScanRequest(arena);
}
constexpr auto ScanRequest::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ScanRequest, _impl_.scans_) +
          decltype(ScanRequest::_impl_.scans_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(ScanRequest), alignof(ScanRequest), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ScanRequest::PlacementNew_,
                                 sizeof(ScanRequest),
                                 alignof(ScanRequest));
  }
}
constexpr auto ScanRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ScanRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ScanRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ScanRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ScanRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ScanRequest>(), &ScanRequest::ByteSizeLong,
              &ScanRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ScanRequest, _impl_._cached_size_),
          false,
      },
      &ScanRequest::kDescriptorMethods,
      &descriptor_table_protos_2finternal_5fedge_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ScanRequest_class_data_ =
        ScanRequest::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL ScanRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ScanRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ScanRequest_class_data_.tc_table);
  return ScanRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
ScanRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ScanRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::internaledge::ScanRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .internaledge.Scan scans = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ScanRequest, _impl_.scans_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .internaledge.Scan scans = 1;
    {PROTOBUF_FIELD_OFFSET(ScanRequest, _impl_.scans_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::internaledge::Scan>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void ScanRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:internaledge.ScanRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.scans_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ScanRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ScanRequest& this_ = static_cast<const ScanRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ScanRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ScanRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:internaledge.ScanRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .internaledge.Scan scans = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_scans_size());
       i < n; i++) {
    const auto& repfield = this_._internal_scans().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:internaledge.ScanRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ScanRequest::ByteSizeLong(const MessageLite& base) {
  const ScanRequest& this_ = static_cast<const ScanRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ScanRequest::ByteSizeLong() const {
  const ScanRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:internaledge.ScanRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .internaledge.Scan scans = 1;
    {
      total_size += 1UL * this_._internal_scans_size();
      for (const auto& msg : this_._internal_scans()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ScanRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ScanRequest*>(&to_msg);
  auto& from = static_cast<const ScanRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:internaledge.ScanRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_scans()->MergeFrom(
      from._internal_scans());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ScanRequest::CopyFrom(const ScanRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:internaledge.ScanRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ScanRequest::InternalSwap(ScanRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.scans_.InternalSwap(&other->_impl_.scans_);
}

::google::protobuf::Metadata ScanRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ProcessingResponse::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ProcessingResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ProcessingResponse, _impl_._has_bits_);
};

ProcessingResponse::ProcessingResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ProcessingResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:internaledge.ProcessingResponse)
}
PROTOBUF_NDEBUG_INLINE ProcessingResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::internaledge::ProcessingResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        successful_scans_{visibility, arena, from.successful_scans_},
        message_(arena, from.message_) {}

ProcessingResponse::ProcessingResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ProcessingResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ProcessingResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ProcessingResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.job_ = ((cached_has_bits & 0x00000002u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.job_)
                : nullptr;
  _impl_.status_ = from._impl_.status_;

  // @@protoc_insertion_point(copy_constructor:internaledge.ProcessingResponse)
}
PROTOBUF_NDEBUG_INLINE ProcessingResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        successful_scans_{visibility, arena},
        message_(arena) {}

inline void ProcessingResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, job_),
           0,
           offsetof(Impl_, status_) -
               offsetof(Impl_, job_) +
               sizeof(Impl_::status_));
}
ProcessingResponse::~ProcessingResponse() {
  // @@protoc_insertion_point(destructor:internaledge.ProcessingResponse)
  SharedDtor(*this);
}
inline void ProcessingResponse::SharedDtor(MessageLite& self) {
  ProcessingResponse& this_ = static_cast<ProcessingResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  delete this_._impl_.job_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ProcessingResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ProcessingResponse(arena);
}
constexpr auto ProcessingResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ProcessingResponse, _impl_.successful_scans_) +
          decltype(ProcessingResponse::_impl_.successful_scans_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(ProcessingResponse), alignof(ProcessingResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ProcessingResponse::PlacementNew_,
                                 sizeof(ProcessingResponse),
                                 alignof(ProcessingResponse));
  }
}
constexpr auto ProcessingResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ProcessingResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ProcessingResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ProcessingResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ProcessingResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ProcessingResponse>(), &ProcessingResponse::ByteSizeLong,
              &ProcessingResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ProcessingResponse, _impl_._cached_size_),
          false,
      },
      &ProcessingResponse::kDescriptorMethods,
      &descriptor_table_protos_2finternal_5fedge_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ProcessingResponse_class_data_ =
        ProcessingResponse::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL ProcessingResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ProcessingResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ProcessingResponse_class_data_.tc_table);
  return ProcessingResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 2, 47, 2>
ProcessingResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ProcessingResponse, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ProcessingResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::internaledge::ProcessingResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional .internaledge.Job job = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 1, 1, PROTOBUF_FIELD_OFFSET(ProcessingResponse, _impl_.job_)}},
    // .internaledge.ProcessingResponse.Status status = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ProcessingResponse, _impl_.status_), 2>(),
     {8, 2, 0, PROTOBUF_FIELD_OFFSET(ProcessingResponse, _impl_.status_)}},
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(ProcessingResponse, _impl_.message_)}},
    // repeated .internaledge.Scan successful_scans = 3;
    {::_pbi::TcParser::FastMtR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(ProcessingResponse, _impl_.successful_scans_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .internaledge.ProcessingResponse.Status status = 1;
    {PROTOBUF_FIELD_OFFSET(ProcessingResponse, _impl_.status_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(ProcessingResponse, _impl_.message_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .internaledge.Scan successful_scans = 3;
    {PROTOBUF_FIELD_OFFSET(ProcessingResponse, _impl_.successful_scans_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .internaledge.Job job = 4;
    {PROTOBUF_FIELD_OFFSET(ProcessingResponse, _impl_.job_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::internaledge::Scan>()},
      {::_pbi::TcParser::GetTable<::internaledge::Job>()},
  }},
  {{
    "\37\0\7\0\0\0\0\0"
    "internaledge.ProcessingResponse"
    "message"
  }},
};
PROTOBUF_NOINLINE void ProcessingResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:internaledge.ProcessingResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.successful_scans_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.message_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      ABSL_DCHECK(_impl_.job_ != nullptr);
      _impl_.job_->Clear();
    }
  }
  _impl_.status_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ProcessingResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ProcessingResponse& this_ = static_cast<const ProcessingResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ProcessingResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ProcessingResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:internaledge.ProcessingResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .internaledge.ProcessingResponse.Status status = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (this_._internal_status() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_status(), target);
    }
  }

  // string message = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_message().empty()) {
      const std::string& _s = this_._internal_message();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "internaledge.ProcessingResponse.message");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // repeated .internaledge.Scan successful_scans = 3;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_successful_scans_size());
       i < n; i++) {
    const auto& repfield = this_._internal_successful_scans().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            3, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional .internaledge.Job job = 4;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *this_._impl_.job_, this_._impl_.job_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:internaledge.ProcessingResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ProcessingResponse::ByteSizeLong(const MessageLite& base) {
  const ProcessingResponse& this_ = static_cast<const ProcessingResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ProcessingResponse::ByteSizeLong() const {
  const ProcessingResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:internaledge.ProcessingResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .internaledge.Scan successful_scans = 3;
    {
      total_size += 1UL * this_._internal_successful_scans_size();
      for (const auto& msg : this_._internal_successful_scans()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    // string message = 2;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_message().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_message());
      }
    }
    // optional .internaledge.Job job = 4;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.job_);
    }
    // .internaledge.ProcessingResponse.Status status = 1;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (this_._internal_status() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ProcessingResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ProcessingResponse*>(&to_msg);
  auto& from = static_cast<const ProcessingResponse&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:internaledge.ProcessingResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_successful_scans()->MergeFrom(
      from._internal_successful_scans());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_message().empty()) {
        _this->_internal_set_message(from._internal_message());
      } else {
        if (_this->_impl_.message_.IsDefault()) {
          _this->_internal_set_message("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      ABSL_DCHECK(from._impl_.job_ != nullptr);
      if (_this->_impl_.job_ == nullptr) {
        _this->_impl_.job_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.job_);
      } else {
        _this->_impl_.job_->MergeFrom(*from._impl_.job_);
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (from._internal_status() != 0) {
        _this->_impl_.status_ = from._impl_.status_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProcessingResponse::CopyFrom(const ProcessingResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:internaledge.ProcessingResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProcessingResponse::InternalSwap(ProcessingResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.successful_scans_.InternalSwap(&other->_impl_.successful_scans_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProcessingResponse, _impl_.status_)
      + sizeof(ProcessingResponse::_impl_.status_)
      - PROTOBUF_FIELD_OFFSET(ProcessingResponse, _impl_.job_)>(
          reinterpret_cast<char*>(&_impl_.job_),
          reinterpret_cast<char*>(&other->_impl_.job_));
}

::google::protobuf::Metadata ProcessingResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace internaledge
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_protos_2finternal_5fedge_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
